---
spring:
  profiles: primary
eureka.client.serviceUrl.defaultZone: http://eureka-primary:8011/eureka/
---
spring:
  profiles: secondary
eureka.client.serviceUrl.defaultZone: http://eureka-secondary:8012/eureka/

---
spring:
  profiles: tertiary
eureka.client.serviceUrl.defaultZone: http://eureka-tertiary:8013/eureka/
